[node0_43]
node0 ns_name=node0 ansible_connection=local
node1 ns_name=node1 ansible_connection=local
node2 ansible_connection=local
node3 ansible_connection=local
node4 ansible_connection=local
node5 ansible_connection=local
node6 ansible_connection=local
node7 ansible_connection=local
node8 ansible_connection=local
node9 ansible_connection=local
node10 ansible_connection=local
node11 ansible_connection=local
node12 ansible_connection=local
node13 ansible_connection=local
node14 ansible_connection=local
node15 ansible_connection=local
node16 ansible_connection=local
node17 ansible_connection=local
node18 ansible_connection=local
node19 ansible_connection=local
node20 ansible_connection=local
node21 ansible_connection=local
node22 ansible_connection=local
node23 ansible_connection=local
node24 ansible_connection=local
node25 ansible_connection=local
node26 ansible_connection=local
node27 ansible_connection=local
node28 ansible_connection=local
node29 ansible_connection=local
node30 ansible_connection=local
node31 ansible_connection=local
node32 ansible_connection=local
node33 ansible_connection=local
node34 ansible_connection=local
node35 ansible_connection=local
node36 ansible_connection=local
node37 ansible_connection=local
node38 ansible_connection=local
node39 ansible_connection=local
node40 ansible_connection=local
node41 ansible_connection=local
node42 ansible_connection=local
node43 ansible_connection=local

