# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paxos.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'paxos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpaxos.proto\"/\n\x12SinglePaxosPayload\x12\r\n\x05value\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\"Q\n\x11MultiPaxosPayload\x12\x0c\n\x04slot\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\x13\n\x0b\x61\x63\x63\x65pted_id\x18\x04 \x01(\x05\"@\n\tSlotState\x12\x13\n\x0b\x61\x63\x63\x65pted_id\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65\x63ided\x18\x03 \x01(\x08\"\xbd\x05\n\x0cPaxosMessage\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.PaxosMessage.Type\x12\x11\n\tsender_id\x18\x02 \x01(\x05\x12\x13\n\x0bproposal_id\x18\x03 \x01(\x03\x12\x0c\n\x04slot\x18\x04 \x01(\x05\x12\x13\n\x0bknown_slots\x18\x05 \x03(\x05\x12\x11\n\tleader_id\x18\x06 \x01(\x05\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x11\n\terror_msg\x18\x08 \x01(\t\x12\x0c\n\x04role\x18\t \x01(\t\x12\r\n\x05state\x18\n \x01(\t\x12%\n\x06single\x18\x0b \x01(\x0b\x32\x13.SinglePaxosPayloadH\x00\x12#\n\x05multi\x18\x0c \x01(\x0b\x32\x12.MultiPaxosPayloadH\x00\x12\'\n\x05slots\x18\r \x03(\x0b\x32\x18.PaxosMessage.SlotsEntry\x1a\x38\n\nSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.SlotState:\x02\x38\x01\"\xaf\x02\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07PREPARE\x10\x01\x12\x0b\n\x07PROMISE\x10\x02\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x03\x12\t\n\x05LEARN\x10\x04\x12\x0c\n\x08LEARN_OK\x10\x05\x12\r\n\tHEARTBEAT\x10\x06\x12\x10\n\x0cHEARTBEAT_OK\x10\x07\x12\x0c\n\x08\x45LECTION\x10\x08\x12\x0f\n\x0b\x45LECTION_OK\x10\t\x12\x0f\n\x0b\x43OORDINATOR\x10\n\x12\x12\n\x0e\x43OORDINATOR_OK\x10\x0b\x12\x10\n\x0cSYNC_REQUEST\x10\x0c\x12\x11\n\rSYNC_RESPONSE\x10\r\x12\x18\n\x14SINGLE_DECREE_RESULT\x10\x0e\x12\x13\n\x0fSINGLE_DECISION\x10\x0f\x12\x17\n\x13MULTI_DECREE_RESULT\x10\x10\x12\x07\n\x03\x45RR\x10\x11\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paxos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAXOSMESSAGE_SLOTSENTRY']._loaded_options = None
  _globals['_PAXOSMESSAGE_SLOTSENTRY']._serialized_options = b'8\001'
  _globals['_SINGLEPAXOSPAYLOAD']._serialized_start=15
  _globals['_SINGLEPAXOSPAYLOAD']._serialized_end=62
  _globals['_MULTIPAXOSPAYLOAD']._serialized_start=64
  _globals['_MULTIPAXOSPAYLOAD']._serialized_end=145
  _globals['_SLOTSTATE']._serialized_start=147
  _globals['_SLOTSTATE']._serialized_end=211
  _globals['_PAXOSMESSAGE']._serialized_start=214
  _globals['_PAXOSMESSAGE']._serialized_end=915
  _globals['_PAXOSMESSAGE_SLOTSENTRY']._serialized_start=542
  _globals['_PAXOSMESSAGE_SLOTSENTRY']._serialized_end=598
  _globals['_PAXOSMESSAGE_TYPE']._serialized_start=601
  _globals['_PAXOSMESSAGE_TYPE']._serialized_end=904
# @@protoc_insertion_point(module_scope)
