- name: Run Paxos cluster on lab machines (no namespaces)
  hosts: pool
  gather_facts: no

  vars:
    inventory_file: /home/campus/s80697/Dokumente/Projekte/Paxos/inventories/inventory_lab_min.yml
    paxos_script: /home/campus/s80697/Dokumente/Projekte/Paxos/src/paxos/paxos_async.py
    python_bin: /home/campus/s80697/Dokumente/Projekte/Paxos/venv/bin/python3
    venv_activate: /home/campus/s80697/Dokumente/Projekte/Paxos/venv/bin/activate

    project_dir: /home/campus/s80697/Dokumente/Projekte/Paxos/

  tasks:
    - name: Check project directory
      ansible.builtin.stat:
        path: /home/campus/s80697/Dokumente/Projekte/Paxos
      register: project_stat

    - debug:
        var: project_stat

    # - name: Show directory content
    #  command: ls -la /home/campus/s80697/Dokumente/Projekte/Paxos

    - name: Show Makefile exists
      command: test -f /home/campus/s80697/Dokumente/Projekte/Paxos/Makefile
      
    - name: Install dependencies
      ansible.builtin.command:
        argv:
          - make
          - -C
          - /home/campus/s80697/Dokumente/Projekte/Paxos
          - install

    - name: Check python exists
      stat:
        path: "{{ python_bin }}"
      register: python_stat

    - name: Launch Paxos node
      ansible.builtin.command:
        argv:
          - "{{ python_bin }}"
          - "{{paxos_script}}"
          - --inventory
          - "{{ inventory_file }}"
          - --netns
          - "{{ node_id }}"
          - --repl
